###########################################################################################
#  ПРИМЕР ЗАПУСКА
#  ansible-playbook -i inventory/ssh.ini playbooks/k8s/1_prepare_hosts_for_k8s.yml
###########################################################################################


---
- name: Prepare hosts for k8s cluster
  hosts: all
  become: true


  roles:
    - prepare_hosts_for_k8s
    
    
