---
- name: Set timezone to Moscow
  timezone:
    name: Europe/Moscow

- name: Verify current timezone
  command: date
  register: current_date
  # ignore_errors: yes

- name: Show the current date and timezone
  debug:
    msg: "Current date and time: {{ current_date.stdout }}"


- name: Update package cache
  apt:
    update_cache: yes


- name: Install necessary packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ base_packages }}"

