---
base_packages:
  - vim
  - tree
  - curl
  - wget
  - net-tools
  - util-linux
  - htop
  - btop
  - iptables
  - apt-transport-https
  - ca-certificates
  - mc
  - gpg
  - iproute2
  - git
  - bash-completion
  - nfs-common
  - tar
  - ntp
  - jq
  - ipvsadm
  - socat
  - lsof
  # - docker.io
