- name: restart service
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: restarted
    daemon_reload: yes
  with_items:
    - "{{ systemd_file }}"
  when: ansible_service_mgr == "systemd"
