########################################################################################################################
# 
#  ДЛЯ DOCKER И LINUX 
#  ansible-playbook -i inventory/ssh.ini playbooks/apps/git_repo/gitlab/gitlab-runner.yml -e "hosts=build-monitor become=true"
#
#
#  ДЛЯ K8S И HELM
#  ansible-playbook playbooks/gitlab-runner/gitlab-runner.yml -e "hosts=localhost become=false"
#
########################################################################################################################

---
- name: download and install gitlab-runner
  hosts: "{{ hosts }}"
  become: "{{ become }}"
  vars: 
    - app_name: gitlab-runner
    

  vars_prompt:
    - name: method
      prompt: "Choose install method: \n1 - linux\n2 - docker\n3 - k8s\n4 - helm\n"
      private: no

    - name: token
      prompt: "Input token for Gitlab Runner register\n"
      private: no  


  tasks:
    - name: check role 
      fail: 
        msg: "ERROR: You should chose only one method (1, 2, 3, 4)."
      when: method not in ['1', '2', '3', '4']

    # - name: server
    #   when: method == '1'
    #   block:
    #     - name: one
    #       include_role:
    #         name: install/linux/install_gitlab-runner

    - name: docker
      when: method == '2'
      block:
        - name: one
          include_role:
            name: install/docker/install_gitlab-runner_docker

    # - name: k8s
    #   when: method == '3'
    #   block:
    #     - name: one
    #       include_role:
    #         name: install/k8s/install_gitlab-runner_k8s

    # - name: helm
    #   when: method == '4'
    #   block:
    #     - name: one
    #       include_role:
    #         name: install/helm/install_gitlab-runner_helm