###############################################################################################
#  
#  ansible-playbook -i inventory/password.ini playbooks/metrics/all/node_exporter.yml -e "hosts=all"
#
###############################################################################################

---
- name: download and install NODE_EXPORTER
  hosts: "{{ hosts }}"
  become: yes
  vars_prompt:
    - name: method
      prompt: "Choose install method: \n1 - in server\n2 - in docker\n"
      private: no 

  tasks:
    - name: check role 
      fail: 
        msg: "ERROR: You should chose only one method (1, 2)."
      when: method not in ['1', '2']

    # - name: server
    #   when: method == '1'
    #   block:
    #     - name: one
    #       include_role:
    #         name: install_node_exporter

    - name: docker
      when: method == '2'
      block:
        - name: one
          include_role:
            name: install_node_exporter_docker
