###########################################################################################
#  ПРИМЕР ЗАПУСКА
#  
#  ПОСЛЕ ВЫПОЛНЕНИЯ ЭТОГО ПЛЕЙБУКА - ВХОД ПО ПАРОЛЮ НА НАСТРАИВАЕМЫЕ СЕРВЕРА БУДЕТ НЕ ДОСТУПЕН
#
#  ansible-playbook -i inventory/password.ini playbooks/basic_setup/basic_setup.yml -e "hosts=all docker=false admins=['adminis','vadim']"
###########################################################################################

---
- name: BASE SETTINGS
  hosts: all
  become: true

  roles:
    - install_base_packages
    - copy_base_configs
    - create_admin_users
    - disable_password_access
