#  ansible-playbook playbooks/basic_setup/basic_setup.yml -e "admins=['adminis','vadim']"

---
- name: BASE SETTINGS
  hosts: all
  become: true



  roles:
    - install_base_packages
    - copy_base_configs
    - create_admin_users
    - disable_password_access
