############################################################################################################################################
#  ПОСЛЕ ВЫПОЛНЕНИЯ ЭТОГО ПЛЕЙБУКА - ВХОД ПО ПАРОЛЮ НА НАСТРАИВАЕМЫЕ СЕРВЕРА БУДЕТ НЕ ДОСТУПЕН
#
#  ansible-playbook -i inventory/password.ini playbooks/basic_setup/basic_setup.yml -e "hosts=all docker=false admins=['adminis','vadim']"
############################################################################################################################################

---
- name: BASE SETTINGS
  hosts: "{{ hosts }}"
  become: true

  roles:
    - basic/install_base_packages
    - basic/copy_base_configs
    - basic/create_admin_users
    - basic/disable_password_access
