##########################################################################################
#
#  ОБЯЗАТЕЛЬНО LOCALHOST тк интерпретатор и kubeconfig берутся из hosts
#  ansible-playbook -i inventory/ssh.ini playbooks/k8s/test-k8s.yml -e "hosts=localhost "
#
###########################################################################################
---
- name: TESTING K8S
  hosts: "{{ hosts }}"
  become: false
  # vars:
    # ansible_python_interpreter: /home/vshakhverdiev/vadim/ansible_v/ansible-env/bin/python3

  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config  
        name: testing2
        api_version: v1
        kind: Namespace
        state: present
      

    - name: Deploy latest version of Prometheus chart inside monitoring namespace (and create it)
      kubernetes.core.helm:
        name: test
        chart_ref: stable/prometheus
        release_namespace: monitoring
        create_namespace: true